version: '3'
volumes:
  mysql-data:
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=loginTemplate
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "80:8080"
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone/loginTemplate?serverTimezone=America/Los_Angeles
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
    build:
      context: './'
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
    restart: always
